### ISSUE TITLE
Logged in user cannot proceed after choosing buyer

### ISSUE THREAD

**Issue by PiQuer** [inbaz/ers#402]
To reproduce: log in, choose a product, continue to shopping cart, continue to "select buyer". The logged in person is pre-selected, add buyer is grayed out (which is fine I guess). Save & continue only opens a completely blank page.

**Comment by PiQuer** [comment]
Maybe related to #380.

**Comment by inbaz** [comment]
Blank page means everytime that there was a php error. So please add the timestamp to the ticket next time such an error occur.

This should be fixed now.

**Comment by PiQuer** [comment]
I can still reproduce this. I'm on http://dev.ers.inbaz.org, is there a more recent version running somewhere? Or do I have to do something locally so that I'm interacting with the newest version?

**Comment by inbaz** [comment]
This is the newest version at the moment. This is strange. I tested it right now and here everything worked well. Do me the favour and test it again. I don't know if I changed anything according to this in the meanwhile.

**Comment by PiQuer** [comment]
Checked with different browser to avoid leftover cookies or whatnot, same result. Really straight forward, after login added a week pass and proceed, gives me the blank page after buyer selection.

I sent you my password by mail, please check with my account.

**Comment by inbaz** [comment]
Argh! I accidentally used the database id instead of the session id. In my case both is 1, therefore this worked for me, but for nobody else. You can change your password again and check again.

**Comment by PiQuer** [comment]
Tested, works. However the order still cannot be completed: #416.
